type: DASH_TYPE_DYNAMIC
media_presentation_duration_sec: 45
periods: {
    id: "pBad"
    start_sec: 0
    duration_sec: 30
    seg_list {
        mult {
            duration: 2
            seg_base { time_scale: 1 }
            start_number: "1"
            timeline: { d: 2 r: 2 }
        }
        segment_urls: { media: "s0.m4s" media_range: "0-100" }
        segment_urls: { media: "s1.m4s" media_range: "101-300" }
    }
    adaptation_sets: { mime_type: "video/mp4" }
}